# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1klTW14axcYoHGN3gIjA4Ay58AGFOpsz5
"""

import math
import pandas as pd
# Create the Play Tennis dataset
data = {
    'Outlook': ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast',
                'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain'],
    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool',
                    'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild'],
    'Humidity': ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal',
                 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High'],
    'Wind': ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong',
             'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Strong'],
    'Play': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
             'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']}
df = pd.DataFrame(data)
#Function to calculate entropy
def entropy(subset):
    total = len(subset)
    if total == 0:
        return 0
    counts = subset.value_counts()
    entropy_value = 0
    for count in counts:
        p = count / total
        entropy_value -= p * math.log2(p)
    return entropy_value
#Calculate overall entropy E(S)
overall_entropy = entropy(df['Play'])
print(f"Overall Entropy E(S): {overall_entropy:.3f}")
#Calculate entropy for each Outlook category
outlook_entropy = 0
for value, subset in df.groupby('Outlook'):
    subset_entropy = entropy(subset['Play'])
    weight = len(subset) / len(df)
    outlook_entropy += weight * subset_entropy
    print(f"Outlook = {value:8s} | Entropy = {subset_entropy:.3f} | Weight = {weight:.3f}")
#Compute Information Gain for Outlook
info_gain_outlook = overall_entropy - outlook_entropy
print(f"\nExpected Entropy for Outlook: {outlook_entropy:.3f}")
print(f"Information Gain for Outlook: {info_gain_outlook:.3f}")